### ISSUE TITLE
First meeting - Tuesday, March 24th 2015

### ISSUE THREAD

**Issue by choldgraf** [knight-lab/journal_club#1]
Hey all - here's a space to talk about / plan out our first journal club.

Right now, the proposed paper is this one:
## Paper

**Frequency-specific hippocampal-prefrontal interactions during associative learning**
Scott L Brincat & Earl K Miller ([link](https://drive.google.com/a/berkeley.edu/file/d/0B8VZ4vaOYWZ3SHdiZkVBVm5Ncms/view?usp=sharing))
## Meeting Time

Tuesday, March 24th, 2015. Time TBD

**Comment by klanderson** [comment]
10am is okay with me
